"""match payment student fields

Revision ID: 197c9696e4da
Revises: 39976fbc27b4
Create Date: 2026-03-22 12:06:53.309036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197c9696e4da'
down_revision: Union[str, None] = '39976fbc27b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('middle_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('father_first_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('father_last_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('mother_first_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('mother_last_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('withdrawal_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('monthly_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('user', sa.Column('is_frozen', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('frozen_at', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('frozen_reason', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('departure_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('return_date', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_user_role_active'), table_name='user')
    op.drop_constraint(op.f('user_student_id_key'), 'user', type_='unique')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_is_frozen'), 'user', ['is_frozen'], unique=False)
    op.create_index('ix_user_phone_number_unique', 'user', ['phone_number'], unique=True, postgresql_where=sa.text('phone_number IS NOT NULL AND is_deleted = false'))
    op.create_index('ix_user_role_active_deleted', 'user', ['role', 'is_active', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_user_student_id'), 'user', ['student_id'], unique=True)
    op.drop_column('user', 'mother_name')
    op.drop_column('user', 'father_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('father_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('mother_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_student_id'), table_name='user')
    op.drop_index('ix_user_role_active_deleted', table_name='user')
    op.drop_index('ix_user_phone_number_unique', table_name='user', postgresql_where=sa.text('phone_number IS NOT NULL AND is_deleted = false'))
    op.drop_index(op.f('ix_user_is_frozen'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    op.create_unique_constraint(op.f('user_student_id_key'), 'user', ['student_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_role_active'), 'user', ['role', 'is_active'], unique=False)
    op.drop_column('user', 'return_date')
    op.drop_column('user', 'departure_date')
    op.drop_column('user', 'frozen_reason')
    op.drop_column('user', 'frozen_at')
    op.drop_column('user', 'is_frozen')
    op.drop_column('user', 'monthly_fee')
    op.drop_column('user', 'withdrawal_date')
    op.drop_column('user', 'mother_last_name')
    op.drop_column('user', 'mother_first_name')
    op.drop_column('user', 'father_last_name')
    op.drop_column('user', 'father_first_name')
    op.drop_column('user', 'middle_name')
    # ### end Alembic commands ###
