"""initial_user_model

Revision ID: 20dfa332b74a
Revises: 
Create Date: 2026-03-21 21:21:33.330437

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20dfa332b74a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('document_id', sa.String(length=20), nullable=False, comment='Passport ID yoki Guvohnoma raqami'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='Telefon raqami (xodimlar uchun majburiy)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=True, comment='Unique student ID (e.g., 2026-001)'),
    sa.Column('grade_id', sa.Integer(), nullable=True, comment='FK to grade table (added in Step 3)'),
    sa.Column('parent_phone', sa.String(length=20), nullable=True, comment='Ota-ona telefon raqami'),
    sa.Column('parent_name', sa.String(length=100), nullable=True, comment="Ota-ona to'liq ismi"),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_document_id'), 'user', ['document_id'], unique=True)
    op.create_index(op.f('ix_user_grade_id'), 'user', ['grade_id'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index('ix_user_role_active', 'user', ['role', 'is_active', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_user_student_id'), 'user', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_student_id'), table_name='user')
    op.drop_index('ix_user_role_active', table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_grade_id'), table_name='user')
    op.drop_index(op.f('ix_user_document_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
