"""add student fields to user model

Revision ID: 39976fbc27b4
Revises: 7fa0be26d7eb
Create Date: 2026-03-22 11:36:12.905162

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39976fbc27b4"
down_revision: Union[str, None] = "7fa0be26d7eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("gender", sa.String(length=10), nullable=True))
    op.add_column("user", sa.Column("student_id", sa.String(length=20), nullable=True))
    op.add_column("user", sa.Column("grade_id", sa.Integer(), nullable=True))
    op.add_column(
        "user", sa.Column("father_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "user", sa.Column("father_phone", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "user", sa.Column("mother_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "user", sa.Column("mother_phone", sa.String(length=20), nullable=True)
    )
    op.add_column("user", sa.Column("address", sa.Text(), nullable=True))
    op.add_column("user", sa.Column("enrollment_date", sa.Date(), nullable=True))
    op.create_index(op.f("ix_user_grade_id"), "user", ["grade_id"], unique=False)
    op.create_unique_constraint("uq_user_student_id", "user", ["student_id"])
    op.create_foreign_key(
        "fk_user_grade_id_grade",
        "user",
        "grade",
        ["grade_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_grade_id_grade", "user", type_="foreignkey")
    op.drop_constraint("uq_user_student_id", "user", type_="unique")
    op.drop_index(op.f("ix_user_grade_id"), table_name="user")
    op.drop_column("user", "enrollment_date")
    op.drop_column("user", "address")
    op.drop_column("user", "mother_phone")
    op.drop_column("user", "mother_name")
    op.drop_column("user", "father_phone")
    op.drop_column("user", "father_name")
    op.drop_column("user", "grade_id")
    op.drop_column("user", "student_id")
    op.drop_column("user", "gender")
    # ### end Alembic commands ###
