"""cleanup_remove_unused_columns

Revision ID: a6b5bffd0402
Revises: 20dfa332b74a
Create Date: 2026-03-21 21:47:52.649163

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6b5bffd0402'
down_revision: Union[str, None] = '20dfa332b74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'document_id',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Passport ID yoki Guvohnoma raqami',
               existing_nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Telefon raqami (xodimlar uchun majburiy)',
               existing_nullable=True)
    op.drop_index(op.f('ix_user_grade_id'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_student_id'), table_name='user')
    op.drop_index(op.f('ix_user_role_active'), table_name='user')
    op.create_index('ix_user_role_active', 'user', ['role', 'is_active'], unique=False)
    op.drop_column('user', 'parent_phone')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'student_id')
    op.drop_column('user', 'grade_id')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'parent_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('parent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment="Ota-ona to'liq ismi"))
    op.add_column('user', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('grade_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='FK to grade table (added in Step 3)'))
    op.add_column('user', sa.Column('student_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Unique student ID (e.g., 2026-001)'))
    op.add_column('user', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('parent_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Ota-ona telefon raqami'))
    op.drop_index('ix_user_role_active', table_name='user')
    op.create_index(op.f('ix_user_role_active'), 'user', ['role', 'is_active', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_user_student_id'), 'user', ['student_id'], unique=True)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_grade_id'), 'user', ['grade_id'], unique=False)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefon raqami (xodimlar uchun majburiy)',
               existing_nullable=True)
    op.alter_column('user', 'document_id',
               existing_type=sa.VARCHAR(length=20),
               comment='Passport ID yoki Guvohnoma raqami',
               existing_nullable=False)
    # ### end Alembic commands ###
