/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSubjectsRouteImport } from './routes/_layout/subjects'
import { Route as LayoutGradesRouteImport } from './routes/_layout/grades'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubjectsRoute = LayoutSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGradesRoute = LayoutGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/grades': typeof LayoutGradesRoute
  '/subjects': typeof LayoutSubjectsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/grades': typeof LayoutGradesRoute
  '/subjects': typeof LayoutSubjectsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/grades': typeof LayoutGradesRoute
  '/_layout/subjects': typeof LayoutSubjectsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/grades' | '/subjects'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/grades' | '/subjects' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/grades'
    | '/_layout/subjects'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subjects': {
      id: '/_layout/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof LayoutSubjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/grades': {
      id: '/_layout/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof LayoutGradesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutGradesRoute: typeof LayoutGradesRoute
  LayoutSubjectsRoute: typeof LayoutSubjectsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutGradesRoute: LayoutGradesRoute,
  LayoutSubjectsRoute: LayoutSubjectsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
