/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ParentLoginRouteImport } from './routes/parent/login'
import { Route as ParentParentRouteImport } from './routes/parent/_parent'
import { Route as LayoutTimetableRouteImport } from './routes/_layout/timetable'
import { Route as LayoutTeachersRouteImport } from './routes/_layout/teachers'
import { Route as LayoutStudentsRouteImport } from './routes/_layout/students'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMonitoringRouteImport } from './routes/_layout/monitoring'
import { Route as LayoutLessonsRouteImport } from './routes/_layout/lessons'
import { Route as LayoutLessonPlanRouteImport } from './routes/_layout/lesson-plan'
import { Route as LayoutAttendanceRouteImport } from './routes/_layout/attendance'
import { Route as ParentParentIndexRouteImport } from './routes/parent/_parent/index'
import { Route as ParentParentTimetableRouteImport } from './routes/parent/_parent/timetable'
import { Route as ParentParentSettingsRouteImport } from './routes/parent/_parent/settings'
import { Route as ParentParentHomeworkRouteImport } from './routes/parent/_parent/homework'
import { Route as ParentParentDisciplineRouteImport } from './routes/parent/_parent/discipline'
import { Route as ParentParentAttendanceRouteImport } from './routes/parent/_parent/attendance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ParentLoginRoute = ParentLoginRouteImport.update({
  id: '/parent/login',
  path: '/parent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentParentRoute = ParentParentRouteImport.update({
  id: '/parent/_parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTimetableRoute = LayoutTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeachersRoute = LayoutTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentsRoute = LayoutStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMonitoringRoute = LayoutMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLessonsRoute = LayoutLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLessonPlanRoute = LayoutLessonPlanRouteImport.update({
  id: '/lesson-plan',
  path: '/lesson-plan',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttendanceRoute = LayoutAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => LayoutRoute,
} as any)
const ParentParentIndexRoute = ParentParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentParentRoute,
} as any)
const ParentParentTimetableRoute = ParentParentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => ParentParentRoute,
} as any)
const ParentParentSettingsRoute = ParentParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentParentRoute,
} as any)
const ParentParentHomeworkRoute = ParentParentHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => ParentParentRoute,
} as any)
const ParentParentDisciplineRoute = ParentParentDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => ParentParentRoute,
} as any)
const ParentParentAttendanceRoute = ParentParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentParentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof LayoutAttendanceRoute
  '/lesson-plan': typeof LayoutLessonPlanRoute
  '/lessons': typeof LayoutLessonsRoute
  '/monitoring': typeof LayoutMonitoringRoute
  '/settings': typeof LayoutSettingsRoute
  '/students': typeof LayoutStudentsRoute
  '/teachers': typeof LayoutTeachersRoute
  '/timetable': typeof LayoutTimetableRoute
  '/parent': typeof ParentParentRouteWithChildren
  '/parent/login': typeof ParentLoginRoute
  '/parent/attendance': typeof ParentParentAttendanceRoute
  '/parent/discipline': typeof ParentParentDisciplineRoute
  '/parent/homework': typeof ParentParentHomeworkRoute
  '/parent/settings': typeof ParentParentSettingsRoute
  '/parent/timetable': typeof ParentParentTimetableRoute
  '/parent/': typeof ParentParentIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof LayoutAttendanceRoute
  '/lesson-plan': typeof LayoutLessonPlanRoute
  '/lessons': typeof LayoutLessonsRoute
  '/monitoring': typeof LayoutMonitoringRoute
  '/settings': typeof LayoutSettingsRoute
  '/students': typeof LayoutStudentsRoute
  '/teachers': typeof LayoutTeachersRoute
  '/timetable': typeof LayoutTimetableRoute
  '/parent/login': typeof ParentLoginRoute
  '/': typeof LayoutIndexRoute
  '/parent/attendance': typeof ParentParentAttendanceRoute
  '/parent/discipline': typeof ParentParentDisciplineRoute
  '/parent/homework': typeof ParentParentHomeworkRoute
  '/parent/settings': typeof ParentParentSettingsRoute
  '/parent/timetable': typeof ParentParentTimetableRoute
  '/parent': typeof ParentParentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/attendance': typeof LayoutAttendanceRoute
  '/_layout/lesson-plan': typeof LayoutLessonPlanRoute
  '/_layout/lessons': typeof LayoutLessonsRoute
  '/_layout/monitoring': typeof LayoutMonitoringRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/students': typeof LayoutStudentsRoute
  '/_layout/teachers': typeof LayoutTeachersRoute
  '/_layout/timetable': typeof LayoutTimetableRoute
  '/parent/_parent': typeof ParentParentRouteWithChildren
  '/parent/login': typeof ParentLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/parent/_parent/attendance': typeof ParentParentAttendanceRoute
  '/parent/_parent/discipline': typeof ParentParentDisciplineRoute
  '/parent/_parent/homework': typeof ParentParentHomeworkRoute
  '/parent/_parent/settings': typeof ParentParentSettingsRoute
  '/parent/_parent/timetable': typeof ParentParentTimetableRoute
  '/parent/_parent/': typeof ParentParentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/lesson-plan'
    | '/lessons'
    | '/monitoring'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/parent'
    | '/parent/login'
    | '/parent/attendance'
    | '/parent/discipline'
    | '/parent/homework'
    | '/parent/settings'
    | '/parent/timetable'
    | '/parent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/lesson-plan'
    | '/lessons'
    | '/monitoring'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/parent/login'
    | '/'
    | '/parent/attendance'
    | '/parent/discipline'
    | '/parent/homework'
    | '/parent/settings'
    | '/parent/timetable'
    | '/parent'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/attendance'
    | '/_layout/lesson-plan'
    | '/_layout/lessons'
    | '/_layout/monitoring'
    | '/_layout/settings'
    | '/_layout/students'
    | '/_layout/teachers'
    | '/_layout/timetable'
    | '/parent/_parent'
    | '/parent/login'
    | '/_layout/'
    | '/parent/_parent/attendance'
    | '/parent/_parent/discipline'
    | '/parent/_parent/homework'
    | '/parent/_parent/settings'
    | '/parent/_parent/timetable'
    | '/parent/_parent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParentParentRoute: typeof ParentParentRouteWithChildren
  ParentLoginRoute: typeof ParentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/parent/login': {
      id: '/parent/login'
      path: '/parent/login'
      fullPath: '/parent/login'
      preLoaderRoute: typeof ParentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/_parent': {
      id: '/parent/_parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/timetable': {
      id: '/_layout/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof LayoutTimetableRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teachers': {
      id: '/_layout/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof LayoutTeachersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/students': {
      id: '/_layout/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof LayoutStudentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/monitoring': {
      id: '/_layout/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof LayoutMonitoringRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lessons': {
      id: '/_layout/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LayoutLessonsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lesson-plan': {
      id: '/_layout/lesson-plan'
      path: '/lesson-plan'
      fullPath: '/lesson-plan'
      preLoaderRoute: typeof LayoutLessonPlanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attendance': {
      id: '/_layout/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof LayoutAttendanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/parent/_parent/': {
      id: '/parent/_parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentParentIndexRouteImport
      parentRoute: typeof ParentParentRoute
    }
    '/parent/_parent/timetable': {
      id: '/parent/_parent/timetable'
      path: '/timetable'
      fullPath: '/parent/timetable'
      preLoaderRoute: typeof ParentParentTimetableRouteImport
      parentRoute: typeof ParentParentRoute
    }
    '/parent/_parent/settings': {
      id: '/parent/_parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentParentSettingsRouteImport
      parentRoute: typeof ParentParentRoute
    }
    '/parent/_parent/homework': {
      id: '/parent/_parent/homework'
      path: '/homework'
      fullPath: '/parent/homework'
      preLoaderRoute: typeof ParentParentHomeworkRouteImport
      parentRoute: typeof ParentParentRoute
    }
    '/parent/_parent/discipline': {
      id: '/parent/_parent/discipline'
      path: '/discipline'
      fullPath: '/parent/discipline'
      preLoaderRoute: typeof ParentParentDisciplineRouteImport
      parentRoute: typeof ParentParentRoute
    }
    '/parent/_parent/attendance': {
      id: '/parent/_parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentParentAttendanceRouteImport
      parentRoute: typeof ParentParentRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAttendanceRoute: typeof LayoutAttendanceRoute
  LayoutLessonPlanRoute: typeof LayoutLessonPlanRoute
  LayoutLessonsRoute: typeof LayoutLessonsRoute
  LayoutMonitoringRoute: typeof LayoutMonitoringRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStudentsRoute: typeof LayoutStudentsRoute
  LayoutTeachersRoute: typeof LayoutTeachersRoute
  LayoutTimetableRoute: typeof LayoutTimetableRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAttendanceRoute: LayoutAttendanceRoute,
  LayoutLessonPlanRoute: LayoutLessonPlanRoute,
  LayoutLessonsRoute: LayoutLessonsRoute,
  LayoutMonitoringRoute: LayoutMonitoringRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStudentsRoute: LayoutStudentsRoute,
  LayoutTeachersRoute: LayoutTeachersRoute,
  LayoutTimetableRoute: LayoutTimetableRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ParentParentRouteChildren {
  ParentParentAttendanceRoute: typeof ParentParentAttendanceRoute
  ParentParentDisciplineRoute: typeof ParentParentDisciplineRoute
  ParentParentHomeworkRoute: typeof ParentParentHomeworkRoute
  ParentParentSettingsRoute: typeof ParentParentSettingsRoute
  ParentParentTimetableRoute: typeof ParentParentTimetableRoute
  ParentParentIndexRoute: typeof ParentParentIndexRoute
}

const ParentParentRouteChildren: ParentParentRouteChildren = {
  ParentParentAttendanceRoute: ParentParentAttendanceRoute,
  ParentParentDisciplineRoute: ParentParentDisciplineRoute,
  ParentParentHomeworkRoute: ParentParentHomeworkRoute,
  ParentParentSettingsRoute: ParentParentSettingsRoute,
  ParentParentTimetableRoute: ParentParentTimetableRoute,
  ParentParentIndexRoute: ParentParentIndexRoute,
}

const ParentParentRouteWithChildren = ParentParentRoute._addFileChildren(
  ParentParentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ParentParentRoute: ParentParentRouteWithChildren,
  ParentLoginRoute: ParentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
